ru =
  signIn: "Вход"
  signin: "вход"
  signOut: "Выход"
  signUp: "Регистрация"
  OR: "Или"
  forgotPassword: "Забыли пароль?"
  emailAddress: "Email"
  emailResetLink: "Сбросить пароль"
  dontHaveAnAccount: "Еще не зарегистрированы?"
  resetYourPassword: "Сбросить пароль"
  updateYourPassword: "Изменить пароль"
  password: "Пароль"
  usernameOrEmail: "Имя пользователя или email"
  email: "Email"
  ifYouAlreadyHaveAnAccount: "Если вы уже зарегистрированы:"
  signUpWithYourEmailAddress: "Вход по email"
  username: "Имя пользователя"
  optional: "Не обязательно"
  signupCode: "Регистрационный код"
  clickAgree: "Нажимая на \"Вход\" вы соглашаетесь с"
  privacyPolicy: "Политика конфиденциальности"
  terms: "Правила использования"
  sign: "Подпись"
  configure: "Настройка"
  with: "с"
  createAccount: "Регистрация"
  and: "и"

  error:
    minChar: "Mинимальная длина пароля - 7 символов."
    pwOneLetter: "В пароле должна быть хотябы одна буква."
    pwOneDigit: "В пароле должна быть хотябы одна цифра."
    usernameRequired: "Необходимо указать имя пользователя."
    emailRequired: "Необходимо указать email."
    signupCodeRequired: "Необходимо указать регистрационный код."
    signupCodeIncorrect: "Указан неверный регистрационный код."
    signInRequired: "Вам необходимо войти в систему для выполнения этих действий."
    usernameIsEmail: "Имя пользователя не может совпадать с email."

T9n.map "ru", ru
